# This is a basic workflow to help you get started with Actions

name: Build and Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Export
        run: npm run export
      - name: Archive Development Artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ github.sha }}
          path: dist
      - name: Webhook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_secret: "front_nuxt_auth"
          webhook_url: "https://dev-nuxt-auth.a.kuroco.app/direct/menu/github/"
          data: '{"run_id":"${{ github.run_id }}", "hash":"${{ github.sha }}"}'
